version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: server_nginx
    ports: 
      - "8088:80"
    volumes: 
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mysql
      - php

  mysql:
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports: 
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  php:
    build: 
      context: .
      dockerfile: Dockerfile
    image: "php:7.4-apache"
    container_name: php-7
    volumes: 
      - ./src:/var/www/html
    restart: unless-stopped
    ports: 
      - "9000:9000"
